version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: hivolunteer-database-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hivolunteer_magic
      POSTGRES_PASSWORD: hivolunteer_magic
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  hive-backend:
    image: europe-west9-docker.pkg.dev/hivolunteer-392013/hivolunteer/back:0.1.0-alpha
    depends_on:
      - postgres
    hostname: hive-backend
    container_name: hivolunteer-hive-backend
    restart: "no"
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hivolunteer_magic
      POSTGRES_PASSWORD: hivolunteer_magic
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

volumes:
  postgres:
    name: nest-db