version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=hivolunteer_magic
      - POSTGRES_PASSWORD=hivolunteer_magic
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres:/var/lib/postgresql/data
  hive-backend:
    image: europe-west9-docker.pkg.dev/hivolunteer-392013/hivolunteer/back:0.2.0-alpha
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=hivolunteer_magic
      - POSTGRES_PASSWORD=hivolunteer_magic
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  hive-frontend:
    build: .
    depends_on:
      - backend
    restart: "no"
    ports:
      - 3000:3000

volumes:
  postgres:
    name: nest-db ~/Repositories/hivolunteer/back 
