name: Build and Test

on:
  push:
    branches: [main, dev, testing]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        recursive: true
    - name: Install dependencies
      run: npm install
    - name: create phantom script
      run: npm pkg set scripts.douille="timeout 15 react-scripts start"
    - name: Build and test
      run: npm run douille || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

