name: Push to repository build container image to registry

on:
  push:
    tags:
    - '^\d+\.\d+\.\d+(-alpha|-beta|)$'
    - '^\d+\.\d+\.\d+(-alpha|-beta|)-dev$'

env:
  DEV_VERSION: ${{ endsWith(github.ref_name, '-dev') }}
  MAIN_VERSION: ${{ ! DEV_VERSION }}

jobs:
  # Push the source code to the container registry.
  push:
    runs-on: ubuntu-latest
    steps:
      # Download repository content to run test on it.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }} # Checkout the source code of the specific tag.

      # Setup the docker emulator.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup the docker builder.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to the Container registry.
      - name: Login to container registry (Google Artifact Registry)
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CONTAINER_REPOSITORY_ENDPOINT }}
          username: _json_key
          password: ${{ secrets.CONTAINER_REPOSITORY_KEY }}

      # Build container image and then push it onto the container registry.
      - name: Build and push
        if: ${{ DEV_VERSION }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            "${{ vars.CONTAINER_REPOSITORY_ENDPOINT }}/${{ github.repository }}:${{ github.ref_name }}"

      # Build container image and then push it onto the container registry as
      # the latest version.
      - name: Build and push
        if: ${{ MAIN_VERSION }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            "${{ vars.CONTAINER_REPOSITORY_ENDPOINT }}/${{ github.repository }}:latest"
            "${{ vars.CONTAINER_REPOSITORY_ENDPOINT }}/${{ github.repository }}:${{ github.ref_name }}"
